window.PROJECTS = [
  {
    id: "asu-shuttle",
    num: "01",
    title: "ASU Shuttle Tracker",
    titleEm: "ASU Shuttle",
    year: "2025",
    role: "Solo UX/UI · Researcher",
    tagline: "Real-time clarity for thousands of campus riders.",
    desc: "End-to-end redesign of ASU's campus shuttle tracker. Mixed-methods research uncovered cluttered maps and hidden arrival times as core pain points, leading to a hi-fi Figma prototype validated through two rounds of usability testing.",
    tags: ["UX Research", "Product Redesign", "Mobile Web", "Case Study"],
    swatch: "ink",
    cover: "Maroon · Live shuttle map",
    preview: "assets/shuttle-cover.jpeg",
    detail: true,
  },
  {
    id: "studio-site",
    num: "02",
    title: "Wildbloom Music Festival App & Admin Tool",
    titleEm: "Wildbloom Music Festival",
    year: "2026",
    role: "Designer · Developer",
    tagline: "Editorial site for an architecture studio.",
    desc: "Identity, type system, and an editorial CMS-driven site for a four-person practice. Hand-coded in Astro because the design called for it.",
    tags: ["Brand", "Web", "Astro", "Type"],
    swatch: "cool",
    cover: "Letterforms on plotter paper",
  },
  {
    id: "kindling",
    num: "03",
    hidden: true,
    title: "Kindling",
    titleEm: "Kindling",
    year: "2024",
    role: "Founding Designer",
    tagline: "Tiny daily rituals for couples, far apart.",
    desc: "Messaging app that swaps endless threads for one shared prompt a day. Designed the prompt library, animations, and brand. Featured by App Store.",
    tags: ["0→1", "iOS", "Visual Design", "Motion"],
    swatch: "blush",
    cover: "Two hands · prompt card",
  },
];
