window.PROJECTS = [
  {
    id: "asu-shuttle",
    num: "01",
    title: "ASU Shuttle Tracker",
    titleEm: "ASU Shuttle",
    year: "2025",
    role: "Solo UX/UI · Researcher",
    tagline: "Real-time clarity for thousands of campus riders.",
    desc: "End-to-end redesign of the campus shuttle tracker. Mixed-methods research, hi-fi Figma prototype, and two rounds of usability testing (SUS + Time on Task) — documented as a full case study.",
    tags: ["UX Research", "Product Design", "Mobile Web", "Course Project"],
    swatch: "ink",
    cover: "Maroon · Live shuttle map",
    detail: true,
  },
  {
    id: "studio-site",
    num: "02",
    title: "Studio Site",
    titleEm: "Studio",
    year: "2024",
    role: "Designer · Developer",
    tagline: "Editorial site for an architecture studio.",
    desc: "Identity, type system, and an editorial CMS-driven site for a four-person practice. Hand-coded in Astro because the design called for it.",
    tags: ["Brand", "Web", "Astro", "Type"],
    swatch: "cool",
    cover: "Letterforms on plotter paper",
  },
  {
    id: "kindling",
    num: "03",
    title: "Kindling",
    titleEm: "Kindling",
    year: "2024",
    role: "Founding Designer",
    tagline: "Tiny daily rituals for couples, far apart.",
    desc: "Messaging app that swaps endless threads for one shared prompt a day. Designed the prompt library, animations, and brand. Featured by App Store.",
    tags: ["0→1", "iOS", "Visual Design", "Motion"],
    swatch: "blush",
    cover: "Two hands · prompt card",
  },
];
